[tool.poetry]
name = "fivetran"
version = "0.7.0"
description = ""
authors = ["Michael Cooper <macoop2363@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9.13"

[tool.poetry.dev-dependencies]
pytest = "^5.0"
pytest-mock = "^3.5.1"
black = "^22.10.0"
mypy = "^0.991"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
