[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[project]
name = "build-essentails-agile-north"
version = "0.0.1"
authors = [
  { name="Stefan Venter", email="stefan@nrth.com" },
]
description = "Python scripts to assist in setting up project dependencies in order to build and run projects"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers"
]

[project.urls]
"Homepage" = "https://github.com/agile-north/build-essentails"
"Bug Tracker" = "https://github.com/agile-north/build-essentails/issues"