[tool.poetry]
name = "gstargets"
version = "0.1.12"
description = ""
authors = ["maghrebi <sajad.faghfoor@gmail.com>"]

packages = [
    { include = "gstargets" },
]

[tool.poetry.dependencies]
python = "^3.x"
zigzag = "^0.3.2"
volprofile = "^0.1.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
