[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "bncutils"
version = "0.0.4"
authors = [
  { name="eugenedg", email="orfray@gmail.com" },
]
description = "Utils for Bulls and Cows game project"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/EugeneDlg/bncweb"
"Bug Tracker" = "https://github.com/EugeneDlg/bncweb"
