[build-system]
requires = ["maturin>=0.13,<0.14"]
build-backend = "maturin"

[project]
name = "neat_notation"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "License :: OSI Approved :: MIT License"
]
version = "0.6.16"
authors = [
  { name="William A. Lim", email="frewtypebbles@gmail.com" },
]
description = "A smart, modular and readable configuration file format for complex multifile solutions."
readme = "README.md"

[project.urls]
"Homepage" = "https://github.com/FrewtyPebbles/Neat-Object-Notation/tree/neat-python"
"Bug Tracker" = "https://github.com/FrewtyPebbles/Neat-Object-Notation/issues"
