[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "DChemPy"
version = "1.1.1"
authors = [
  { name="Yiheng Dai", email="dyh12380@163.com" },
]
description = "A packaged kit for chemical machine learning made by Yiheng Dai in Xiamen University."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/horizon233/DChemPy"
"Bug Tracker" = "https://github.com/horizon233/DChemPy/issues"