[tool.poetry]
name = "hoppr"
version = "1.6.2"
description = "A tool for defining, verifying, and transferring software dependencies between environments."
authors = ["LMCO Open Source <open.source@lmco.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://hoppr.dev/"
repository = "https://gitlab.com/lmco/hoppr/hoppr"

keywords = [
    "packaging",
    "reports",
    "build dependencies",
    "software bill of materials"
]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Information Technology",
    "Topic :: Communications :: File Sharing",
    "Topic :: Software Development :: Version Control",
    "Topic :: System :: Software Distribution"
]

[[tool.poetry.packages]]
include = "hoppr"

[tool.poetry.scripts]
hopctl = "hoppr.main:app"

[tool.mypy]

[tool.poetry.dependencies]
python = "^3.10"
typer = "^0.7.0"
requests = "^2.27.1"
PyYAML = "^6.0"
jsonschema = "^4.4.0"
oras = "^0.0.17"
urllib3 = "^1.26.9"
click = "8.1.3"
types-PyYAML = "^6.0.5"
packageurl-python = "^0.10.0"
pydantic = {extras = ["email"], version = "^1.9.0"}
hoppr-cyclonedx-models = "0.2.10"

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"
black = "^22.1.0"
pylint = "^2.12.2"
coverage = "^6.3.2"
mypy = "^0.961"
pre-commit = "^2.17.0"
types-requests = "^2.27.15"
isort = "^5.10.1"
setuptools = "^65.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
