[tool.poetry]
name = "astream"
version = "0.5.1"
description = ""
authors = ["Pedro Batista <pedrovhb@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
wrapt = "^1.14.1"
decorator = "^5.1.1"
lazy-object-proxy = "^1.8.0"
mypy = "^0.991"
PyHeat = "^0.2"
asyncio = "^3.4.3"

[tool.poetry.dev-dependencies]
black = "^22.10.0"
pytest = "^7.2.0"
pytest-asyncio = "^0.20.1"
hypothesis = "^6.56.4"
pre-commit = "^2.20.0"
bump2version = "^1.0.1"
usort = "^1.0.5"
flake8 = "^5.0.4"
coverage = "^6.5.0"
pylint = "^2.15.5"
loguru = "^0.6.0"
rich = "^12.6.0"
jurigged = {path = "../jurigged"}
ptpython = "^3.0.20"
ipython = "^8.6.0"
jupyterlab = "^3.5.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
python_version = "3.10"
warn_unused_configs = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
strict = true
show_error_codes = true
show_traceback = true


[tool.black]
line-length = 100
target-version = ['py310']

[tool.usort]
line_length = 100

[tool.flake8]
max-line-length = 100


[pytest]
asyncio_mode = "auto"
