[tool.poetry]
name = "clean_menu"
version = "0.2.1"
description = "Minimal library fot making menus within the console"
authors = ["PetchouDev <petchou91d@gmail.com>"]
packages = [
    { include = "clean_menu" },
]
readme = "README.md"
repository = "https://github.com/PetchouDev/cleanMenu"


[tool.poetry.dependencies]
python = "^3.9"
termcolor = "^2.1.0"
pynput = "^1.7.6"
art = "^5.7"
colorama = "^0.4.6"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[[tool.poetry.source]]
name = "morpion-game"
url = "https://github.com/P-C-Corp/Games/Morpion"
default = false
secondary = false

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"